#!/bin/bash
# quick script to process the aggregated results file to output a LaTeX table.
# Benchmark,probes, min length,total chains, total possible states,reachable states(?), states
# visited,chains larger than 1,mean chain length (only > 1,stopped because dead
# end,stopped because all possible visited

while read x; do
bench=$(basename $(echo $x | awk -F: /:/'{print $1}') | awk -F. '{print $1}')
results=$(echo $x | awk -F: '{print $2}')
trimmed_results=${results//\,/&}

echo $bench \& $trimmed_results \\\\
done
